server:
   port: 8180
   context-path: /nb-water-admin
spring:
   application:
      name: microservice-water-admin
   datasource:
      url: jdbc:oracle:thin:@172.168.12.100:1521:oracle
      username: nbwater
      password: nbwater
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: oracle.jdbc.driver.OracleDriver
   mvc:
      view:
         prefix: /WEB-INF/jsp/
         suffix: .jsp
   redis:
      port: 6379
      host: 172.168.12.100
      timeout: 30000
   jmx: 
      enabled: false  
   cloud:
      nacos:
       discovery:
        server-addr: 172.168.12.108:8848
      
mybatis:
   config-location: classpath:mybatis/mybatis-config.xml
   mapper-locations: classpath:com/ets/**/mapper*.xml

logging:
   config: classpath:logback.xml
   
